version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - '3247:3247'
    environment:
      PORT: 3247
      HOST: 0.0.0.0
volumes:
  node_modules:
    driver: local